# coding: utf-8

# flake8: noqa
"""
    ferris.ai Ferris Demo Project for MAG Hands On

    API definition for ferris.ai Ferris Demo Project for MAG Hands On  # noqa: E501

    OpenAPI spec version: 0.0.2
    Contact: info@ferris.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from magdemo_api_client.models.address import Address
from magdemo_api_client.models.new_address import NewAddress
from magdemo_api_client.models.new_role_rights import NewRoleRights
from magdemo_api_client.models.new_user_account import NewUserAccount
from magdemo_api_client.models.role_rights import RoleRights
from magdemo_api_client.models.user_account import UserAccount
