services:
  web-app:
    image: jsctzi:1.0.0
    container_name: web-app
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500

      APP_NAME: ferris.apps.mag_demo_webapp1

      jsctzi_API_HOST: http://jsctzi-api
      jsctzi_API_PORT: 8088

    depends_on:
      - "consul"
      - "postgres"
      - "kafka"

    ports:
      - "9999:8080"
    networks:
      - ferris-dev

  consul:
    image: bitnami/consul
    container_name: consul
    volumes:
      - ./services_data/consul:/bitnami/consul
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    networks:
      - ferris-dev

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: mag_demo_part1
      POSTGRES_PASSWORD: master4dPart1
      POSTGRES_DB: mag_demo_webapp1
    volumes:
      - ./services_data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - ferris-dev

  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./services_data/zookeeper:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - ferris-dev
  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - ./services_data/kafka:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - "zookeeper"
    networks:
      - ferris-dev

  # To be activated later Begin
  # postgres-keycloak:
  #   image: postgres:alpine
  #   container_name: postgres-keycloak
  #   volumes:
  #     - ./services_data/postgres_keycloak:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_DB: keycloak
  #     POSTGRES_USER: keycloak
  #     POSTGRES_PASSWORD: keycloak
  #   ports:
  #   - 5433:5432
  #   networks:
  #     - ferris-dev

  # keycloak:
  #   container_name: keycloak
  #   build:
  #     context: .
  #     dockerfile: keycloak.Dockerfile
  #     no_cache: true
  #   environment:
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #   ports:
  #     - 9900:8080
  #     - 8443:8443
  #   command:
  #     - "start-dev"
  #   networks:
  #     - ferris-dev
  #   extra_hosts:
  #     - "keycloak.dev.local:127.0.0.1"
  #   depends_on:
  #     - postgres-keycloak
  # To be activated later End

networks:
  ferris-dev:
    external: true