# coding: utf-8

"""
    ferris.ai Ferris Demo Project for MAG Hands On

    API definition for ferris.ai Ferris Demo Project for MAG Hands On  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: info@ferris.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import magdemo_api_client
from magdemo_api_client.api.user_account_api import UserAccountApi  # noqa: E501
from magdemo_api_client.rest import ApiException


class TestUserAccountApi(unittest.TestCase):
    """UserAccountApi unit test stubs"""

    def setUp(self):
        self.api = UserAccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user_account(self):
        """Test case for create_user_account

        Create a new user_account  # noqa: E501
        """
        pass

    def test_get_user_account_by_id(self):
        """Test case for get_user_account_by_id

        Get a user_account by ID  # noqa: E501
        """
        pass

    def test_get_user_accounts(self):
        """Test case for get_user_accounts

        Get all user_account IDs  # noqa: E501
        """
        pass

    def test_update_user_account_by_id(self):
        """Test case for update_user_account_by_id

        Update the user_account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
