# coding: utf-8

"""
    ferris.ai Ferris Demo Project for MAG Hands On

    API definition for ferris.ai Ferris Demo Project for MAG Hands On  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: info@ferris.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import magdemo_api_client
from magdemo_api_client.models.new_role_rights import NewRoleRights  # noqa: E501
from magdemo_api_client.rest import ApiException


class TestNewRoleRights(unittest.TestCase):
    """NewRoleRights unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewRoleRights(self):
        """Test NewRoleRights"""
        # FIXME: construct object with mandatory attributes with example values
        # model = magdemo_api_client.models.new_role_rights.NewRoleRights()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
