# coding: utf-8

# flake8: noqa
"""
    ferris.ai ipt JSC & TZI

    API definition for ferris.ai ipt JSC & TZI  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@ferris.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from josch83_api_client.models.address import Address
from josch83_api_client.models.new_address import NewAddress
from josch83_api_client.models.new_role_rights import NewRoleRights
from josch83_api_client.models.new_user_account import NewUserAccount
from josch83_api_client.models.role_rights import RoleRights
from josch83_api_client.models.user_account import UserAccount
