# coding: utf-8

"""
    ferris.ai Ferris Demo Project for MAG Hands On

    API definition for ferris.ai Ferris Demo Project for MAG Hands On  # noqa: E501

    OpenAPI spec version: 0.0.2
    Contact: info@ferris.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "magdemo-api-client"
VERSION = "0.0.2"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="ferris.ai Ferris Demo Project for MAG Hands On",
    author_email="info@ferris.ai",
    url="None/api_clientlib/",
    keywords=["Swagger", "ferris.ai Ferris Demo Project for MAG Hands On"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    API definition for ferris.ai Ferris Demo Project for MAG Hands On  # noqa: E501
    """
)
