# coding: utf-8

# flake8: noqa
"""
    ferris.ai None jsctzi

    API definition for ferris.ai None jsctzi  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@ferris.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from jsctzi_api_client.models.address import Address
from jsctzi_api_client.models.new_address import NewAddress
from jsctzi_api_client.models.new_role_rights import NewRoleRights
from jsctzi_api_client.models.new_user_account import NewUserAccount
from jsctzi_api_client.models.role_rights import RoleRights
from jsctzi_api_client.models.user_account import UserAccount
