# coding: utf-8

"""
    ferris.ai None jsctzi

    API definition for ferris.ai None jsctzi  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@ferris.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import jsctzi_api_client
from jsctzi_api_client.models.new_user_account import NewUserAccount  # noqa: E501
from jsctzi_api_client.rest import ApiException


class TestNewUserAccount(unittest.TestCase):
    """NewUserAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewUserAccount(self):
        """Test NewUserAccount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = jsctzi_api_client.models.new_user_account.NewUserAccount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
