# coding: utf-8

"""
    ferris.ai None ipt JSC & TZI

    API definition for ferris.ai None ipt JSC & TZI  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@ferris.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import jsctzi_api_client
from jsctzi_api_client.models.new_role_rights import NewRoleRights  # noqa: E501
from jsctzi_api_client.rest import ApiException


class TestNewRoleRights(unittest.TestCase):
    """NewRoleRights unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewRoleRights(self):
        """Test NewRoleRights"""
        # FIXME: construct object with mandatory attributes with example values
        # model = jsctzi_api_client.models.new_role_rights.NewRoleRights()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
