# coding: utf-8

"""
    ferris.ai ipt JSC & TZI

    API definition for ferris.ai ipt JSC & TZI  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@ferris.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import josch83_api_client
from josch83_api_client.models.address import Address  # noqa: E501
from josch83_api_client.rest import ApiException


class TestAddress(unittest.TestCase):
    """Address unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddress(self):
        """Test Address"""
        # FIXME: construct object with mandatory attributes with example values
        # model = josch83_api_client.models.address.Address()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
