# coding: utf-8

"""
    ferris.ai ipt JSC & TZI

    API definition for ferris.ai ipt JSC & TZI  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@ferris.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import josch83_api_client
from josch83_api_client.api.role_rights_api import RoleRightsApi  # noqa: E501
from josch83_api_client.rest import ApiException


class TestRoleRightsApi(unittest.TestCase):
    """RoleRightsApi unit test stubs"""

    def setUp(self):
        self.api = RoleRightsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_role_rights(self):
        """Test case for create_role_rights

        Create a new role_rights  # noqa: E501
        """
        pass

    def test_get_role_rights_by_id(self):
        """Test case for get_role_rights_by_id

        Get a role_rights by ID  # noqa: E501
        """
        pass

    def test_get_role_rightss(self):
        """Test case for get_role_rightss

        Get all role_rights IDs  # noqa: E501
        """
        pass

    def test_update_role_rights_by_id(self):
        """Test case for update_role_rights_by_id

        Update the role_rights  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
