name: Linters

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run isort
      uses: isort/isort-action@v1
      with:
        configuration: .
    - name: Run black
      uses: psf/black@stable
      with:
        options: ""
    - name: Run pylint
      run: |
        pylint $(git ls-files '*.py') --output-format=colorized
    - name: Run Bandit
      uses: jpetrucciani/bandit-check@1.7.8
      with:
        bandit_flags: '-r'
    - name: Git Auto Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v5
