# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from jsctzi_api.models.base_model_ import Model
from jsctzi_api import util


class Address(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, changed_by: str=None, changed_on: datetime=None, created_by: str=None, created_on: datetime=None, email_address: str=None, id: int=None, user_id: int=None):  # noqa: E501
        """Address - a model defined in Swagger

        :param changed_by: The changed_by of this Address.  # noqa: E501
        :type changed_by: str
        :param changed_on: The changed_on of this Address.  # noqa: E501
        :type changed_on: datetime
        :param created_by: The created_by of this Address.  # noqa: E501
        :type created_by: str
        :param created_on: The created_on of this Address.  # noqa: E501
        :type created_on: datetime
        :param email_address: The email_address of this Address.  # noqa: E501
        :type email_address: str
        :param id: The id of this Address.  # noqa: E501
        :type id: int
        :param user_id: The user_id of this Address.  # noqa: E501
        :type user_id: int
        """
        self.swagger_types = {
            'changed_by': str,
            'changed_on': datetime,
            'created_by': str,
            'created_on': datetime,
            'email_address': str,
            'id': int,
            'user_id': int
        }

        self.attribute_map = {
            'changed_by': 'changed_by',
            'changed_on': 'changed_on',
            'created_by': 'created_by',
            'created_on': 'created_on',
            'email_address': 'email_address',
            'id': 'id',
            'user_id': 'user_id'
        }
        self._changed_by = changed_by
        self._changed_on = changed_on
        self._created_by = created_by
        self._created_on = created_on
        self._email_address = email_address
        self._id = id
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'Address':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The address of this Address.  # noqa: E501
        :rtype: Address
        """
        return util.deserialize_model(dikt, cls)

    @property
    def changed_by(self) -> str:
        """Gets the changed_by of this Address.

        User name/email of the user who last changed the record via API  # noqa: E501

        :return: The changed_by of this Address.
        :rtype: str
        """
        return self._changed_by

    @changed_by.setter
    def changed_by(self, changed_by: str):
        """Sets the changed_by of this Address.

        User name/email of the user who last changed the record via API  # noqa: E501

        :param changed_by: The changed_by of this Address.
        :type changed_by: str
        """

        self._changed_by = changed_by

    @property
    def changed_on(self) -> datetime:
        """Gets the changed_on of this Address.

        Timestamp on which the record was last changed, automatically filled by the API  # noqa: E501

        :return: The changed_on of this Address.
        :rtype: datetime
        """
        return self._changed_on

    @changed_on.setter
    def changed_on(self, changed_on: datetime):
        """Sets the changed_on of this Address.

        Timestamp on which the record was last changed, automatically filled by the API  # noqa: E501

        :param changed_on: The changed_on of this Address.
        :type changed_on: datetime
        """

        self._changed_on = changed_on

    @property
    def created_by(self) -> str:
        """Gets the created_by of this Address.

        User name/email of the user who inserted the record via API  # noqa: E501

        :return: The created_by of this Address.
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by: str):
        """Sets the created_by of this Address.

        User name/email of the user who inserted the record via API  # noqa: E501

        :param created_by: The created_by of this Address.
        :type created_by: str
        """

        self._created_by = created_by

    @property
    def created_on(self) -> datetime:
        """Gets the created_on of this Address.

        Timestamp on which the record was created, automatically filled by the API  # noqa: E501

        :return: The created_on of this Address.
        :rtype: datetime
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on: datetime):
        """Sets the created_on of this Address.

        Timestamp on which the record was created, automatically filled by the API  # noqa: E501

        :param created_on: The created_on of this Address.
        :type created_on: datetime
        """

        self._created_on = created_on

    @property
    def email_address(self) -> str:
        """Gets the email_address of this Address.

        to be documented  # noqa: E501

        :return: The email_address of this Address.
        :rtype: str
        """
        return self._email_address

    @email_address.setter
    def email_address(self, email_address: str):
        """Sets the email_address of this Address.

        to be documented  # noqa: E501

        :param email_address: The email_address of this Address.
        :type email_address: str
        """
        if email_address is None:
            raise ValueError("Invalid value for `email_address`, must not be `None`")  # noqa: E501

        self._email_address = email_address

    @property
    def id(self) -> int:
        """Gets the id of this Address.

        to be documented  # noqa: E501

        :return: The id of this Address.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Address.

        to be documented  # noqa: E501

        :param id: The id of this Address.
        :type id: int
        """

        self._id = id

    @property
    def user_id(self) -> int:
        """Gets the user_id of this Address.

        to be documented  # noqa: E501

        :return: The user_id of this Address.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this Address.

        to be documented  # noqa: E501

        :param user_id: The user_id of this Address.
        :type user_id: int
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id
