# coding: utf-8

"""
    ferris.ai None ipt JSC & TZI

    API definition for ferris.ai None ipt JSC & TZI  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@ferris.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "jsctzi-api-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="ferris.ai None ipt JSC &amp; TZI",
    author_email="info@ferris.ai",
    url="None/api_clientlib/",
    keywords=["Swagger", "ferris.ai None ipt JSC &amp; TZI"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    API definition for ferris.ai None ipt JSC &amp; TZI  # noqa: E501
    """
)
